# Generated by Django 2.1.15 on 2025-11-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplyapp', '0002_auto_20251113_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorderhistory',
            old_name='product_id',
            new_name='raw_material',
        ),
        migrations.AddField(
            model_name='purchaseorderhistory',
            name='raw_material_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
