# Generated by Django 2.1.15 on 2025-11-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplyapp', '0003_auto_20251113_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderhistory',
            name='delivery_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
