# Generated by Django 2.1.15 on 2025-11-13 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplyapp', '0004_purchaseorderhistory_delivery_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Distributor',
        ),
    ]
