# Generated by Django 2.1.15 on 2025-11-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplyapp', '0005_delete_distributor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorderhistory',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='customerorderhistory',
            name='product_id',
        ),
        migrations.AddField(
            model_name='customerorderhistory',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customerorderhistory',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customerorderhistory',
            name='distributor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customerorderhistory',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customerorderhistory',
            name='tracking_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
