# Generated by Django 2.1.15 on 2025-11-16 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplyapp', '0006_auto_20251115_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerorderhistory',
            old_name='distributor_name',
            new_name='distributor_id',
        ),
        migrations.RenameField(
            model_name='customerorderhistory',
            old_name='product_name',
            new_name='product_id',
        ),
    ]
