# Generated by Django 2.1.15 on 2025-11-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplyapp', '0007_auto_20251116_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorderhistory',
            name='distributor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customerorderhistory',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
